### ISSUE TITLE
error running sleuth_fit

### ISSUE THREAD

**Issue by marypiper** [pachterlab/sleuth#69]
Hi,

I am trying to run sleuth on the output of sailfish. I can successfully run the sleuth_prep() command, but I get an error when I try to run sleuth_fit(). 

The sleuth_prep() command I am running is: `so <- sleuth_prep(sfdata, design, target_mapping = t2g)` and the sleuth_fit() command is `sleuth_fit(so)`. 

The error output for the sleuth_fit() command is: `Error in solve.default(t(X) %*% X) : Lapack routine dgesv: system is exactly singular: U[2,2] = 0`.

I am attaching my Rscript and linking the R object output from the sleuth_prep() command. Could you please let me know if you have any suggestions for debugging?

sleuth_prep() output R object: https://dl.dropboxusercontent.com/u/204381225/sleuth_prep_output.RData

 sleuth script: [sleuth.txt](https://github.com/pachterlab/sleuth/files/291845/sleuth.txt)

Thank you for your help,
Mary

**Comment by apcamargo** [comment]
I'm getting this error in the latest devel version.

`Error in solve.default(t(X) %*% X) : 
  Lapack routine dgesv: system is exactly singular: U[4,4] = 0`

**Comment by warrenmcg** [comment]
@apcamargo, the bug was introduced by a typo that has now been fixed in the latest devel version.

**Comment by apcamargo** [comment]
I'm still getting this error. The only thing that I could do to not get it was to remove a covariate that has three categories.

**Comment by pimentel** [comment]
@apcamargo 

could you please provide more information? specifically:

- what was your sleuth command?
- where was this happening? please also provide a `traceback()`
- please provide your `sample_to_condition` data frame

my guess is that the model matrix that is derived from the sample to condition data frame and formula is not full rank.

**Comment by apcamargo** [comment]
This is my script:
```
library("sleuth")

setwd("/home/apcamargo/Documents/sleuth/")
base_dir <- "/home/apcamargo/Documents/sleuth"
sample_id <- dir(file.path(base_dir,"Quantification"))
kal_dirs <- sapply(sample_id, function(id) file.path(base_dir, "Quantification", id))
tissue <- c('a', 'a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'a', 'a', 'a')
stage <- c('adult', 'adult', 'adult', 'adult', 'adult', 'adult', 'adult', 'adult', 'adult', 'adult', 'adult', 'adult', 'nb', 'nb', 'nb', 'nb', 'nb', 'nb')
sex <- c('female', 'female', 'male', 'male', 'male', 'female', 'male', 'female', 'male', 'female', 'male', 'female', 'mix', 'mix', 'mix', 'mix', 'mix', 'mix')

df <- data.frame("sample"=sample_id, "tissue"=tissue, "stage"=stage, "sex"=sex)
df <- dplyr::mutate(df, path=kal_dirs)

###

model <- sleuth_prep(df, ~ stage + tissue + sex)
model <- sleuth_fit(model)
```

traceback:
```
3: solve.default(t(X) %*% X)
2: solve(t(X) %*% X)
1: sleuth_fit(model)
```
model$sample_to_covariates
```
> model$sample_to_covariates
        sample tissue stage    sex
1    1A      a adult female
2    1B      a adult female
3    1C      a adult   male
4    1D      a adult   male
5    1E      a adult   male
6    1F      a adult female
7    2A      b adult   male
8    2B      b adult female
9    2C      b adult   male
10   2D      b adult female
11   2E      b adult   male
12   2F      b adult female
13   3A      b    nb    mix
14   3B      b    nb    mix
15   3C      b    nb    mix
16   4A      a    nb    mix
17   4B      a    nb    mix
18   4C      a    nb    mix
```

When I remove the 'sex' covariate, the script runs fine

**Comment by pimentel** [comment]
@apcamargo 

The design matrix in this case is not full rank. Notice that `sexmix` is exactly the same as `stagenb`:

```
R> tmp <- read.table(text = "tissue stage    sex
+ 1A      a adult female
+ 1B      a adult female
+ 1C      a adult   male
+ 1D      a adult   male
+ 1E      a adult   male
+ 1F      a adult female
+ 2A      b adult   male
+ 2B      b adult female
+ 2C      b adult   male
+ 2D      b adult female
+ 2E      b adult   male
+ 2F      b adult female
+ 3A      b    nb    mix
+ 3B      b    nb    mix
+ 3C      b    nb    mix
+ 4A      a    nb    mix
+ 4B      a    nb    mix
+ 4C      a    nb    mix", header = TRUE)
R> model.matrix(~ stage + tissue + sex, tmp)
   (Intercept) stagenb tissueb sexmale sexmix
1A           1       0       0       0      0
1B           1       0       0       0      0
1C           1       0       0       1      0
1D           1       0       0       1      0
1E           1       0       0       1      0
1F           1       0       0       0      0
2A           1       0       1       1      0
2B           1       0       1       0      0
2C           1       0       1       1      0
2D           1       0       1       0      0
2E           1       0       1       1      0
2F           1       0       1       0      0
3A           1       1       1       0      1
3B           1       1       1       0      1
3C           1       1       1       0      1
4A           1       1       0       0      1
4B           1       1       0       0      1
4C           1       1       0       0      1
```

Thus, you can't fit a linear model until you make `sexmix` independent from the other columns.

Notice that you don't have this issue if you drop `sex` as you suggest:

```
R> model.matrix(~ stage + tissue, tmp)
   (Intercept) stagenb tissueb
1A           1       0       0
1B           1       0       0
1C           1       0       0
1D           1       0       0
1E           1       0       0
1F           1       0       0
2A           1       0       1
2B           1       0       1
2C           1       0       1
2D           1       0       1
2E           1       0       1
2F           1       0       1
3A           1       1       1
3B           1       1       1
3C           1       1       1
4A           1       1       0
4B           1       1       0
4C           1       1       0
```

**Comment by apcamargo** [comment]
Oh, now I understand! I didn't know that a covariate with three categories generates two columns (sexmale and sexmix).

Thank you!

**Comment by linrio** [comment]
I have mat a similar problem:
```
pcor(c(1,2,3,4,5,6,7,8,9), cov(init_data))
Error in solve.default(S[u, u]) : 
  Lapack routine dgesv: system is exactly singular: U[1,1] = 0
```
The `init_data` is a DataFrame, it has 10 columns, I wanna to use `pcor()` function.
How to fix this problem ?
