### ISSUE TITLE
deferentially expressed genes with sleuth- RStudio 

### ISSUE THREAD

**Issue by alaalhalawany** [pachterlab/sleuth#98]
Hello 
I need a help in analyzing deferentially expressed genes with
I have a Kallisto data with 6 folders and an identification file for info. as the following:

run_accession	experiment_accession	Index	condition	sample
pC1-a	pC1-6a	Rip-GFP/Col-a	control	Xiao-Ning
pC2-b	pC1-6b	Rip-GFP/Col-b	control	Xiao-Ning
pC3-c	pC1-6c	Rip-GFP/Col-c	control	Xiao-Ning
p9-1	p9-1-6g	Rip-OX9-1	p9	Xiao-Ning
p9-2	p9-2-6h	Rip-OX9-2	p9	Xiao-Ning
p9-3	p9-3-6j	Rip-OX9-3	p9	Xiao-Ning

and my task is analyzing them with the sleuth on R studio 
I have a certain script as the following: 

source("http://bioconductor.org/biocLite.R")
biocLite("rhdf5")
biocLite("biomaRt")

biocLite("devtools")    # only if devtools not yet installed
install.packages('devtools')
devtools::install_github('pachterlab/sleuth')
install.packages('shiny')

library("sleuth")

base_dir <- "C:/Users/asus/Desktop/data"

sample_id <- dir(file.path(base_dir,"results"))

kal_dirs <- sapply(sample_id, function(id) file.path(base_dir, "results", id, "kallisto"))

s2c <- read.table(file.path(base_dir, "hiseq_info_rip_p9.txt" ), header = TRUE, stringsAsFactors=FALSE)
s2c <- dplyr::select(s2c, sample = run_accession, condition)
s2c
s2c <- dplyr::mutate(s2c, path = kal_dirs)
print(s2c)
so <- sleuth_prep(s2c, ~ condition)
so <- sleuth_fit(so)
so <- sleuth_wt(so, 'conditionp1')
models(so)
sleuth_live(so)
results_table <- sleuth_results(so, 'conditionp9')

----------------------------------------------------------------------

and the script is working but I am facing a problem as the following: 

reading in kallisto results
......
Error in check_kal_pack(kal_list) : 
  Inconsistent number of transcripts. Please make sure you used the same index everywhere.
> so <- sleuth_fit(so)
Error in is(obj, "sleuth") : object 'so' not found
> so <- sleuth_wt(so, 'control	Xiao-Ning')
Error in is(obj, "sleuth") : object 'so' not found
> models(so)
Error in models(so) : object 'so' not found
> sleuth_live(so)
Error in is(obj, "sleuth") : object 'so' not found
> results_table <- sleuth_results(so, 'Xiao-Ning')
Error in is(obj, "sleuth") : object 'so' not found

I would appreciate any small details that could help, thank you!

**Comment by warrenmcg** [comment]
Hi @alaalhalawany,

Do you have the script for how you ran `kallisto`? When you look at the `run_info.json` for each `kallisto` folder, there is a parameter called `n_targets`. Is this the same for all samples? If not, do you have a record of the "log" messages when Kallisto is run. It's clear from the error messages that there is at least one Kallisto sample that had a different number of transcripts analyzed, and it's only going back to Kallisto that you'll be able to discover the issue.

Once those issues are dealt with, then we can get to the bottom of your error.

Hope that helps!
Warren

**Comment by pimentel** [comment]
ping @alaalhalawany

**Comment by golrokh51** [comment]
I have the same problem and this is my n_targets:
	"n_targets": 65896,
	"n_targets": 65896,
	"n_targets": 65896,
	"n_targets": 65896,
	"n_targets": 65896,
	"n_targets": 65896,
	"n_targets": 65896,
	"n_targets": 65896,
	"n_targets": 65896,
	"n_targets": 65896,
	"n_targets": 65896,
	"n_targets": 65896,
	"n_targets": 65896,
	"n_targets": 65896,
	"n_targets": 65896,
	"n_targets": 65896,
and I have no error in kallisto logs

**Comment by golrokh51** [comment]
Done!

**Comment by warrenmcg** [comment]
Done meaning you sent the files (I have not received them yet, so there was probably an issue there) or done meaning you found the issue and it had to do with the R version you were using?

**Comment by golrokh51** [comment]
I sent it to warren-mcgee@fsm.northwestern.edu.
no it is not resolved the problem, with the last version of R, Sleuth is not available at all. 
I am testing with 2 other R version to see if it is R version.

**Comment by golrokh51** [comment]
> library(sleuth)
> meta <- read.table("meta.tab", header=TRUE)
> meta$path <- as.character(meta$path)
> so <- sleuth_prep(meta, ~ time)
reading in kallisto results
dropping unused factor levels
................
Error in check_kal_pack(kal_list) : 
  Inconsistent number of transcripts. Please make sure you used the same index everywhere.
In addition: Warning message:
In check_kal_pack(kal_list) :
  More than one version of kallisto was used: 0.44.0
NULL
>

        r/3.3.3 same error
        r/3.4.0 same error
        r/3.4.3 same error
        r/3.5.0 sleuth is not available

**Comment by golrokh51** [comment]
Sleuth is working, I think the problem was with the bootstrap. But it is not working with r/3.5.0 . I tried with r/3.3.3 and it is working well with this R version. Thanks enormously :)

**Comment by warrenmcg** [comment]
HI @golrokh51, I know we spoke off-line, but can you confirm if you're still getting this error? We're trying to clear out issues before the next major release.

**Comment by ig161** [comment]
Hello, i have the same issue - same number of n_targets and just one version of kallisto, but it keeps on telling me this error. I was running r/3.6.0. How did you solve this again, @golrokh51 ? @warrenmcg
